config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :tags
  resources :formats
  resources :videos
  resources :ideas
  resources :votes
  resources :users, only: [:show]
  resources :videovotes

  get 'ideas/index/:id', to: 'ideas#index', via: :get

  root 'ideas#index'
end

app/models/idea.rb
class Idea < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :formats
  has_and_belongs_to_many :users
  has_many :videos
  has_many :votes

  validates :title, presence: true,
            length: { minimum: 3,
                      maximum: 90,
                      too_short: "Must have at least 3 characters",
                      too_long: "Must have fewer than 50 characters"
                    }
  validates :summary, presence: true,
            length: { minimum: 10,
                      maximum: 140,
                      too_short: "Must have at least 10 characters",
                      too_long: "Must have fewer than 140 characters"
                    }
  validates :content, presence: true,
            length: { minimum: 10,
                      maximum: 10000,
                      too_short: "Must have at least 100 characters",
                      too_long: "You have reached your character limitation. Please visit our <%= /pro %> page for pro plans."
                    }
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
    @vote = Vote.new
    @videovote = Videovote.new

    if params[:id] == nil
      if Idea.all.length == 0
        @idea = Idea.new
      else
        @idea = Idea.find(Idea.all.first.id)
      end
    else
      @idea = Idea.find(params[:id])
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.create(idea_params)
    if @idea.save
      respond_to do |format|
        format.html do
          flash[:notice] = "Idea Created."
          redirect_to idea_path(@idea)
        end
        format.json { render :json => @idea, :status => 201 }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render :json => @idea.errors, :status => 422 }
      end
    end
  end

  def show
    @idea = Idea.friendly.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @ideas }
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(params[:idea])
      respond_to do |format|
        format.html do
          flash[:notice] = "Idea updated."
          redirect_to idea_path(@idea)
        end
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render 'edit' }
        format.json { render :json => @idea.errors, :status => 422 }
      end
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = "Idea deleted."
        redirect_to ideas_path
      end
      format.json { head :no_content }
    end
  end

private

  def idea_params
    params.require(:idea).permit(:title, :content, :summary, :published, :slug)
  end
end

app/views/ideas/_form.html.erb
<%= form_for @idea do |f| %>
  <div><%= f.label :title %><br />
  <%= f.text_area :title, cols: 40 %></div>
  <div><%= f.label :summary %><br />
  <%= f.text_area :summary, cols: 60 %></div>
  <div><%= f.label :content %><br />
  <%= f.text_area(:content, cols: 60, rows: 10) %></div>
  <%= f.submit "Create idea" %>
<% end %>

app/views/ideas/_videos.html.erb
<% @idea.videos.each do |video| %>
  <span class="rightSideNav">
    <p>Video uploader User_ID: <%= video.user_id %></p>
    <p>Parent Idea idea_id : <%= video.idea_id %></p>
  </span>
  <br>
    <iframe width="560" height="315" src=<%= "#{video.video_url}" %> frameborder="0" allowfullscreen></iframe>
  <hr>
  <% if current_user != nil %>
    <%= form_for @videovote do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :video_id, :value => video.id %>
      <%= f.submit "Vote Up!", :class => "btn btn-primary btn-sm" %>
    <% end %>
  <% end %>
  <p> <%= link_to "Currently has: #{video.videovotes.length}", video_path(video) %></p>
<% end %>

app/views/ideas/index.html.erb
<div class="row">

  <div class="col-sm-6">
    <ul class="home">
      <h4><%= link_to "New Idea", new_idea_path %></h4>
      <h2><center>IDEA<center></h2>
      <hr>
      <% @ideas.each do |idea| %>
        <span class="rightSideNav">
          <% idea.users.each  do |user| %>
            <%= user.username %>
          <% end %>
        </span>
        <br>
        <li><%= link_to idea.title, "/ideas/index/#{idea.id}", id: "idea_link", remote: true %></a><br>
          <p><%= idea.summary %></p>
        <% if current_user != nil %>
<!--Glyphicon not working! -->
          <span class="glyphicon glyphicon-arrow-up"></span>
          <%= link_to "Vote this Up!", new_vote_path %>

            <%= form_for @vote do |f| %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :idea_id, :value => idea.id %>
              <%= f.submit "Vote Up!", :class => "btn btn-primary btn-sm" %>
            <% end %>
          <% end %>
          <p> <%= link_to "Currently has: #{idea.votes.length}", idea_path(idea) %></p>
        <hr>
        </li>
      <% end %>
    </ul>
  </div>


  <div class="col-sm-6">
    <ul>
      <h4><%= link_to "New Video", new_video_path %></h4>
      <h2><center>VIDEO<center></h2>
      <hr>
      <div id="idea_videos">
        <%= render("videos") %>
      </div>
    </ul>
  </div>
</div>

app/views/ideas/index.js.erb
$("#idea_videos").html('<%= j render("videos") %>');

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<h3><em><%= @idea.summary %></em></h3>
  <p><%= @idea.content %></p>
<h4>Past Votes</h4>
<span class="glyphicon glyphicon-arrow-up"></span>
<span class="fa fa-arrow-up"></span>
<span class="ionicons ion-ios7-arrow-up"></span>

<br />
<ul class="list">
  <% @idea.votes.each do |vote| %>
    <li><%= link_to vote.user.username, root_path %>
        <p> Time Voted: <%= vote.how_long %></P></li>
  <% end %>
</ul>